apiVersion: v1
data:
  range-global: 192.168.1.2-192.168.1.20
kind: ConfigMap
metadata:
  creationTimestamp: "2025-11-12T21:26:43Z"
  name: kubevip
  namespace: kube-system
  resourceVersion: "551038"
  uid: 89e1049a-b079-49b1-b623-c8efcdd43889
