apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-storage
  labels:
    app.kubernetes.io/name: grafana-storage
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce # required
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.1.59
    path: /mnt/TrueNAS-pool/local/grafana-data